Fix errors when importing the package in a DOMless environment (e.g. Node)
Change `exports` "import" field to "default"

This fixes the following error I'm getting when building my Next.js app that uses this package:

```
my-app:build: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/benface/my-app/node_modules/style-observer/package.json
my-app:build:     at exportsNotFound (node:internal/modules/esm/resolve:314:10)
my-app:build:     at packageExportsResolve (node:internal/modules/esm/resolve:604:13)
my-app:build:     at resolveExports (node:internal/modules/cjs/loader:657:36)
my-app:build:     at Function._findPath (node:internal/modules/cjs/loader:749:31)
my-app:build:     at Function.<anonymous> (node:internal/modules/cjs/loader:1387:27)
my-app:build:     at /Users/benface/my-app/node_modules/.pnpm/next@14.2.28_@babel+core@7.27.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/require-hook.js:55:36
my-app:build:     at Function.resolve (node:internal/modules/helpers:145:19)
my-app:build:     at _resolve (/Users/benface/my-app/node_modules/.pnpm/jiti@1.21.7/node_modules/jiti/dist/jiti.js:1:246378)
my-app:build:     at jiti (/Users/benface/my-app/node_modules/.pnpm/jiti@1.21.7/node_modules/jiti/dist/jiti.js:1:249092)
```

`default` must be last

Try to fix `ReferenceError: document is not defined` in SSR

Fix syntax errors

Fix “ReferenceError: requestAnimationFrame is not defined” in SSR

Another one

Even more defensive

This actually prevents an error, not when building in Next, but when running tests with Vitest and jsdom…

Address Lea’s feedback

Update src/util/detect-bugs/transitionrun-loop.js

Update src/util/detect-bugs/transitionrun-loop.js

Tweaks

Try to make package side-effect-free

Clean up

Oops

Fix bug + make it closer to previous syntax

Add `"sideEffects": false` to package.json

Restore `allowDiscrete` const

Update package.json

Update gentle-register-property.js

Update JSDoc for consistency

Make `observe` synchronous again

`Bugs.detectAll()` => `Bugs.detect()` + return results

`export default class Bugs`

Keep behavior of defaulting bugs to `true`, instead of `false`

Remove redundant `@private` annotations

Add empty line between unrelated blocks of code

Fix “globalThis.CSS?.supports is not a function” in Node

Simplify

Revert to `bugs` spelling

Revert to not `_BUG` suffix

Remove side effects experiment (#117)

Remove `”sideEffects”: false` from `package.json` because it’s kind of a lie

Co-Authored-By: Lea Verou <lea@verou.me>
Co-Authored-By: Dmitry Sharabin <dmitrysharabin@gmail.com>